schoenef_html_to_pdf:
  provider: pdfrocket
  timeout: 40
  apikey: "%env(resolve:HTML2PDF_API_KEY)%"
  default_options:
    shrinking: false
    dpi: 300
    image_quality: 100
    page_size: A4
    zoom: 1.335